---
title: "Fantasy Football Draft Model"
author: "Bryson Burr"
date: "January 21, 2025"
output:
  pdf_document:
    toc: true
  html_document:
    number_sections: true
    toc: true
editor_options:
  chunk_output_type: inline
---

# Set Up and Data Import

## Package loading
``` {r library, message = FALSE, warning = FALSE}
mydir <- getwd()

setwd(mydir)
library(tidyverse)
library(rvest)
library(stringr)
library(rjson)
```

## Get data using nflfastR

``` {r getting nflfastR}
testing <- nflfastR::load_player_stats(2024)

start_year <- 2010
end_year <- 2024

all_season_stats <- list()

for(year in start_year:end_year) {
  cat("Loading data for season:", year, "\n")  # Print progress
  season_stats <- nflfastR::load_player_stats(year)
  
  all_season_stats[[as.character(year)]] <- season_stats
}
```

# Clean Data

```{r clean nflfastR data}
colnames(testing)
# find which position groups are in data
unique(testing$position_group)

# want to get rid of spec, db, ol, lb, and dl

# keep the following columns:"player_id", "player_display_name", "position”, "recent_team",  "season",  "week", "season_type”, "completions", "attempts", "passing_yards", "passing_tds", "interceptions"  "sack_fumbles_lost", "passing_2pt_conversions”, "carries", "rushing_yards", "rushing_tds"               "rushing_fumbles_lost”, "rushing_2pt_conversions", "receptions", "targets"                     "receiving_yards", "receiving_tds", "receiving_fumbles_lost", "receiving_2pt_conversions"   "fantasy_points_ppr" 

# consolidate fumble columns to one singular column
# create full season stats for every player
# add games played column for full season stats



clean_stats <- function(df) {
  df |>
    filter(position_group %in% c("QB", "RB", "TE", "WR"),
           season_type == "REG") |>
    select("player_id", "player_display_name", "position", "recent_team", "season", "week", "season_type", 
           "completions", "attempts", "passing_yards", "passing_tds", "interceptions", "sack_fumbles_lost",
           "passing_2pt_conversions", "carries", "rushing_yards", "rushing_tds", "rushing_fumbles_lost", 
           "rushing_2pt_conversions", "receptions", "targets", "receiving_yards", "receiving_tds", 
           "receiving_fumbles_lost", "receiving_2pt_conversions", "fantasy_points_ppr") |>
    mutate(fumbles_lost = sack_fumbles_lost + rushing_fumbles_lost + receiving_fumbles_lost) |>
    select(-sack_fumbles_lost, -rushing_fumbles_lost, -receiving_fumbles_lost) 
}

processed_list <- map(all_season_stats, clean_stats)


# keep only current players for seasons
#using nflreadr to get current rosters
current_players <- nflreadr::load_rosters(2024) |>
  filter(position %in% c("QB", "RB", "TE", "WR"))
colnames(current_players)

# function to filter for current players
filter_current_players <- function(df, roster_ids) {
  df |>
    inner_join(roster_ids, by = c("player_id" = "gsis_id"))
}
# apply function to list to filter for current players
filtered_seasons <- lapply(processed_list, filter_current_players, roster_ids = current_players)

```




```{r future df}
### HERE IS THE CODE TO CREATE A DF FOR TOTAL SEASON STATS
    group_by(player_id) |>
    summarize(total_completions = sum(completions, na.rm = TRUE),
              total_attempts = sum(attempts, na.rm = TRUE),
              total_passing_yards = sum(passing_yards, na.rm = TRUE),
              total_passing_tds = sum(passing_tds, na.rm = TRUE),
              total_interceptions = sum(interceptions, na.rm = TRUE),
              total_passing_2pt_conversions = sum(passing_2pt_conversions, na.rm = TRUE),
              total_carries = sum(carries, na.rm = TRUE),
              total_rushing_yards = sum(rushing_yards, na.rm = TRUE),
              total_rushing_tds = sum(rushing_tds, na.rm = TRUE),
              total_rushing_2pt_conversions = sum(rushing_2pt_conversions, na.rm = TRUE),
              total_receptions = sum(receptions, na.rm = TRUE),
              total_targets = sum(targets, na.rm = TRUE),
              total_receiving_yards = sum(receiving_yards, na.rm = TRUE),
              total_receiving_tds = sum(receiving_tds, na.rm = TRUE),
              total_receiving_2pt_conversions = sum(receiving_2pt_conversions, na.rm = TRUE),
              total_fantasy_points_ppr = sum(fantasy_points_ppr, na.rm = TRUE),
              total_fumbles_lost = sum(fumbles_lost, na.rm = TRUE),
              total_games_played = n_distinct(week),
              .groups = "drop"
              )
```
